### ISSUE TITLE
Kann man den OptolinkDuoBlock gegen angemessene Aufwandsentschädigung erwerben?

### ISSUE THREAD

**Issue by Gandralf1969** [vich-667/OptolinkDuoBlock#1]
Habe dasselbe auch schon im USB_Duo_Sniffer - Forum gefragt, aber vielleicht ist diese Weiterentwicklung sogar *noch* interessanter!

Leider fehlt mir das technische Geschick für einen Nachbau, wäre daher für die Möglichkeit das komplette Teil oder zumindest vorgefertigte Komponenten davon beziehen zu können ser dankbar.

Ein OptoLink-Kabel selbst hätte ich schon (war bei der Vitoconnect mit dabei), es fehlt aber die Möglichkeit des "Mitlesens".
Selbst Steuerbefehle an die Vitocal zu schicken ist *NICHT* mein Ziel, sondern ich will wirklich nur das Mitlesen, wass die Anlage über OPTOLINK und Vitoconnect an VIESSMANN sendet.

**Comment by vich-667** [comment]
Mit diese Erweiterung des USB_Duo_Sniffers besitzt zusätlich die Möglichkeit, die kommunikation der Vitoconnect zu blockieren um direkt mit der Vitocal kommunizieren zu können. Fertig kann ich die aber leider nicht anbieten. Da hilft nur löten.

Eine alternative ist die Proxy Lösung die im Forum irgendwo angesprochen wurde:

`Vitocal--->Optic<---Optolink Kabel--->USB<--Raspi-->Serielle-Pins<---CP 2102--->USB<--Vitoconnect`

So ein CP2102 Plattinchen ist für wenig Geld incl. Kabel um es mit dem Raspi zu verbinden auf [ebay](https://www.ebay.de/itm/255323594516?itmmeta=01HWB8NJCGEQYNYHZ7CY5ZJ58C&hash=item3b7278df14:g:fSMAAOSwVBVb3bFd&itmprp=enc%3AAQAJAAAAwHHEuwyuGVeJQ9gay5dP5DQe29LI9VUmrGLgo01D8yelA6Bt0BxvUOe%2FF0PMQIc3OLIoge5t7EY8JQ7WFFeLLrBvaOTxJygVCiKvImzfIgIvgFN73Pm6lF2UY%2BJgRquGTXEaa2Efaq1H%2FFuhQxG05hSAEwm5K3%2B%2FB6E0vKfI9kWKfI10KGKm%2F2l%2FCv%2Bkx6Hc74KiJsW6BpKwRmX%2FT%2BMG1TdeBlVjVm%2BUAf%2F1gvNN9KNN3cjR3W%2FxygflnewndfyeNg%3D%3D%7Ctkp%3ABk9SR9qm1ujiYw) zu finden. RX mit TX verbinden und umgekehrt sowie GND, das ist ausreichend.

Ich hatte das in meiner Software zwar mal vorgesehen, aber nie genutzt. [Proxy optomac](https://github.com/vich-667/OptolinkDuoBlock/blob/pub-main/Software/vito_monitor_ctrl/optolink_mac/optolink_mac_proxy.py) Deswegen kann ich da keine weitere Unterstüzung abieten. Es gab aber irgendwo ein kleines Python Projekt um den reinen Proxy zu realiseiren.
